# Generated by Django 5.0.1 on 2024-01-05 21:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last Name')),
                ('image_url', models.ImageField(default='images/users/default.png', upload_to='images/users', verbose_name='Image')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('role', models.CharField(choices=[('ADM', 'Admin'), ('MGR', 'Manager'), ('SRP', 'Sales Representative'), ('COK', 'Cook'), ('RDR', 'Rider'), ('CST', 'Customer')], default='CST', max_length=3)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(help_text='House Number', max_length=20, verbose_name='House Number')),
                ('full_name', models.CharField(help_text='Full Name of the Address (i.e. Recipient)', max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(help_text='Phone Number at the Address', max_length=150, verbose_name='Phone Number')),
                ('post_code', models.CharField(help_text='Postal Code of the Address', max_length=20, verbose_name='Post Code')),
                ('address_line_1', models.CharField(help_text='Address Line #1', max_length=250, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(help_text='Address Line #2', max_length=250, verbose_name='Address Line 2')),
                ('town_city', models.CharField(help_text='Town/City/State', max_length=150, verbose_name='Town/City/State')),
                ('delivery_instructions', models.CharField(help_text='The instructions on how to get items delivered at the address', max_length=250, verbose_name='Delivery Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('default', models.BooleanField(default=False, help_text='Is this the default address of user/customer', verbose_name='Default')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Select a User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
