# Generated by Django 5.0.1 on 2024-01-05 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_no', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('delivered', models.BooleanField(default=False, help_text='Change delivery status', verbose_name='Delivery Status')),
                ('is_active', models.BooleanField(default=True, help_text='Change delivery visibility', verbose_name='Delivery visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('order', models.ForeignKey(help_text='Select an Order', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(help_text='Select a Staff Driver', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Delivery Staff')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
