# Generated by Django 5.0.1 on 2024-01-05 21:55

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required and unique', max_length=50, unique=True, verbose_name='Category Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Category (safe) URL')),
                ('description', models.CharField(help_text='Required and unique', max_length=255, verbose_name='Category Description')),
                ('is_active', models.BooleanField(default=True, help_text='Change category visibility', verbose_name='Category visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Meal Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Meal (safe) URL')),
                ('description', ckeditor.fields.RichTextField(help_text='Describe the meal', unique=True, verbose_name='Meal Description')),
                ('price', models.IntegerField(help_text='Give the Price of the Meal', verbose_name='Meal Price')),
                ('image_url', models.ImageField(default='images/meals/default.png', upload_to='images/meals', verbose_name='Meal Image')),
                ('is_active', models.BooleanField(default=True, help_text='Change meal visibility', verbose_name='Meal visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('category', models.ForeignKey(help_text='Select a Category', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='menu.category', verbose_name='Meal Category')),
                ('user', models.ForeignKey(help_text='Select a User', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL, verbose_name='Meal Creator')),
            ],
            options={
                'verbose_name': 'Meal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_prepared', models.IntegerField(help_text='Give the Units of Meal Prepared', verbose_name='Units of Meal Prepared')),
                ('units_left', models.IntegerField(help_text='Give the Units of Meal Left', verbose_name='Units of Meal Left')),
                ('is_active', models.BooleanField(default=True, help_text='Change meal inventory visibility', verbose_name='Meal Inventory visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('meal', models.OneToOneField(help_text='Select a Meal', on_delete=django.db.models.deletion.CASCADE, to='menu.meal', verbose_name='Meal for the Inventory')),
                ('user', models.ForeignKey(help_text='Select a User', on_delete=django.db.models.deletion.CASCADE, related_name='meal_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Meal Inventory Creator')),
            ],
            options={
                'verbose_name': 'Meal Inventory',
                'verbose_name_plural': 'Meal Inventories',
                'ordering': ['-created_at'],
            },
        ),
    ]
